spring:
  application:
    name: crud

  datasource:
    url: jdbc:mysql://localhost:3308/crud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/khacngoc
        registration:
          keycloak:
            client-id: crud_server
            client-secret: fluURBwVXZzQNno1IAgXNQ2yzOW8voLn

keycloak:
  auth-server-url: http://localhost:8180
  realm: khacngoc
  resource: crud_server
  credentials:
    secret: fluURBwVXZzQNno1IAgXNQ2yzOW8voLn
  bearer-only: true
  admin:
    client-id: admin-cli
    username: admin
    password: admin
    secret: kKKuZY1SuvsuOWs36hsCFhFhthYKpc5m
  policy-enforcer-config:
    enforcement-mode: ENFORCING
